version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq/

volumes:
  rabbitmq-volume: