# datasource properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news-api-db
    username: user
    password: 1234

  # jpa properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # rabbitmq properties
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1234

# App properties
newsapi:
  jwt:
    secret: ${JWT_SECRET:12341234123412341234123412341234}
    expiration: ${JWT_EXPIRATION:86400000}
